# Generated by Django 6.0.3 on 2026-04-03 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resizing', 'Resizing Image'), ('forwarding', 'Running Forward Pipeline'), ('encrypting', 'Encrypting Watermark'), ('svd', 'Applying SVD'), ('pso', 'Optimizing with PSO'), ('embedding', 'Embedding Watermark'), ('thresholding', 'Thresholding'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('alpha_star', models.FloatField(blank=True, null=True)),
                ('tamper_threshold', models.FloatField(blank=True, null=True)),
                ('pso_particles', models.IntegerField(blank=True, null=True)),
                ('pso_iterations', models.IntegerField(blank=True, null=True)),
                ('pso_cost', models.FloatField(blank=True, null=True)),
                ('dtcwt_levels', models.IntegerField(blank=True, null=True)),
                ('n_blocks', models.IntegerField(blank=True, null=True)),
                ('sv_length', models.IntegerField(blank=True, null=True)),
                ('LL_shape_h', models.IntegerField(blank=True, null=True)),
                ('LL_shape_w', models.IntegerField(blank=True, null=True)),
                ('max_benign_drift', models.FloatField(blank=True, null=True)),
                ('auto_threshold', models.FloatField(blank=True, null=True)),
                ('final_threshold', models.FloatField(blank=True, null=True)),
                ('watermark_shape', models.JSONField(blank=True, null=True)),
                ('henon_a', models.FloatField(blank=True, null=True)),
                ('henon_b', models.FloatField(blank=True, null=True)),
                ('psnr_value', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('progress', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
