# Generated by Django 6.0.3 on 2026-04-06 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermarking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TamperVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verifying', 'Running Tamper Verification'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('is_tampered', models.BooleanField(blank=True, null=True)),
                ('tampered_frac', models.FloatField(blank=True, null=True)),
                ('tamper_grid_flat', models.JSONField(blank=True, null=True)),
                ('grid_rows', models.IntegerField(blank=True, null=True)),
                ('grid_cols', models.IntegerField(blank=True, null=True)),
                ('sv_deltas_flat', models.JSONField(blank=True, null=True)),
                ('tamper_threshold_used', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_process', models.ForeignKey(blank=True, help_text='The embedding process whose .npz key is used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='watermarking.imageprocess')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tamper_verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
