# Generated by Django 6.0.3 on 2026-04-06 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermarking', '0002_tamperverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatermarkExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('extracting', 'Extracting Watermark'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('alpha_star', models.FloatField(blank=True, null=True)),
                ('n_blocks', models.IntegerField(blank=True, null=True)),
                ('sv_length', models.IntegerField(blank=True, null=True)),
                ('watermark_shape', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_process', models.ForeignKey(blank=True, help_text='The embedding process whose .npz key is used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extractions', to='watermarking.imageprocess')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watermark_extractions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
